apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-eks-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: code2cloud
        image: public.ecr.aws/e9q5a7k6/code2cloud:5189bccbc1e2552e8b2abb1763f36297c58d3b0d
